import Header from '../components/Header'
import type { Metadata } from 'next'
import './global.css'

export const metadata: Metadata = {
  title: "Zora's Travels",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        {children}
      </body>
    </html>
  )
}
